#!/bin/bash

# Extract data using jq and process with awk and sed
jq -r '. | "\(.name) \(.types[0].type.name) \(.weight) \(.height)"' data.json | 
awk '{
    name = $1
    type = $2
    formatted_weight = $3/10
    formatted_height = $4/10
    print name " is of type " type ", weighs " formatted_weight "kg, and is " formatted_height "m tall."
}' | 
sed 's/^./\U&/'